### PR TITLE
Fix deprecation warning, drop sbt 1.0.x support

### LINKED ISSUE #231: Migrate to new slash syntax
Since sbt 1.5 the `in` syntax has been deprecated and should be updated to the newer slash syntax. I'm currently getting the following warnings when using sbt 1.7.1:
```
       [warn] /app/.sbt_home/plugins/HerokuBuildpackPlugin.scala:6:20: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     sources in doc in Compile := List(),
       [warn]                    ^
       [warn] /app/.sbt_home/plugins/HerokuBuildpackPlugin.scala:6:13: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     sources in doc in Compile := List(),
       [warn]             ^
       [warn] /app/.sbt_home/plugins/HerokuBuildpackPlugin.scala:7:21: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     publishArtifact in packageDoc := false,
       [warn]                     ^
       [warn] /app/.sbt_home/plugins/HerokuBuildpackPlugin.scala:8:21: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     publishArtifact in packageSrc := false
```

### PR DESCRIPTION
**Pull request by Malax**
As reported in #231, the sbt plugin injected by this buildpack causes deprecation warnings with sbt `>= 1.5`. 

The fix requires the plugin to use the slash syntax which is only supported in sbt since `1.1`. Since version `1.0` is EOL for some time now and a migration to `1.1` or later is trivial, this PR removes sbt `1.0` support instead of providing a special plugin for that version. Error messages have been adjusted accordingly.

Fixes #231.
Ref: GUS-W-14387696

### CODE REVIEW

File: lib/common.sh [hunk 1]
```diff
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 SBT_0_VERSION_PATTERN='sbt\.version=\(0\.1[1-3]\.[0-9]*\(-[a-zA-Z0-9_]*\)*\)$'
-SBT_1_VERSION_PATTERN='sbt\.version=\(1\.[0-9]*\.[0-9]*\(-[a-zA-Z0-9_]*\)*\)$'
+SBT_1_VERSION_PATTERN='sbt\.version=\(1\.[1-9]*\.[0-9]*\(-[a-zA-Z0-9_]*\)*\)$'
```
Comment (edmorley) [inline lib/common.sh:4]: Before v1 versions like `1.10.x` were supported, but now they won't. 

ie: Should the regex be like this?

```suggestion
SBT_1_VERSION_PATTERN='sbt\.version=\(1\.[1-9][0-9]*\.[0-9]*\(-[a-zA-Z0-9_]*\)*\)$'
```

Also it seems like some of the `*` usages should instead be `+`, otherwise versions like `1..0` would be accepted?

Comment (Malax) [reply lib/common.sh]: Yeah, the regex is (and wasn't) great. I updated them in [541f9be](https://github.com/heroku/heroku-buildpack-scala/pull/232/commits/541f9be784fb684bae5c652903ae3f5233f564be).  👍🏻

**Review by edmorley — APPROVED** [review]
